# Generated by Django 5.1.7 on 2025-03-19 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_userprofile_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='features',
            name='property',
        ),
        migrations.AddField(
            model_name='features',
            name='property',
            field=models.ManyToManyField(to='app.property'),
        ),
    ]
